### ISSUE TITLE
Does not work at archive pages

### ISSUE THREAD

**Issue by drumzonly** [senlin/so-responsive-content#3]
Hi, just tried out your SO-responsive-content plugin. Works very well, but it seems that it does not work for (as an example) archive by month pages or category pages.
Is there a solution for that?

**Comment by senlin** [comment]
> it does not work for (as an example) archive by month pages or category pages

The plugin adds shortcode buttons to the editor, archive pages cannot be edited in the editor as they are templates and therefore this "_doesn't work_".

So this has in fact nothing to do with the plugin.

You can try and add the classes that this plugin outputs to the archive template of your (child)theme.
